# Generated by Django 3.1.7 on 2021-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('main_h', models.TextField()),
                ('main_p_1', models.TextField()),
                ('main_p_2', models.TextField()),
                ('main_p_3', models.TextField()),
                ('footer', models.TextField()),
            ],
        ),
    ]
