# Generated by Django 3.1.7 on 2021-03-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0003_auto_20210316_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='header',
            field=models.TextField(help_text='Введите текст:'),
        ),
    ]
