# Generated by Django 3.1.7 on 2021-03-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0004_auto_20210317_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='header',
            field=models.TextField(),
        ),
    ]
