# Generated by Django 3.1.7 on 2021-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0005_auto_20210317_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='test_1/static/')),
                ('menu_text_1', models.TextField()),
                ('menu_text_2', models.TextField()),
                ('menu_text_3', models.TextField()),
                ('menu_text_4', models.TextField()),
                ('text_lk', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.FileField(upload_to='test_1/static/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_p_1',
            field=models.FileField(upload_to='test_1/static/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_p_2',
            field=models.FileField(upload_to='test_1/static/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_p_3',
            field=models.FileField(upload_to='test_1/static/'),
        ),
    ]
