# Generated by Django 3.1.7 on 2021-03-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0006_auto_20210317_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_h1', models.TextField()),
                ('index_h2', models.TextField()),
                ('index_a_1', models.TextField()),
                ('index_a_2', models.TextField()),
                ('index_img', models.FileField(upload_to='test_1/static/')),
            ],
        ),
    ]
