# Generated by Django 3.1.7 on 2021-03-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0007_mainindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forwhom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwhom_h1', models.TextField()),
                ('forwhom_h2', models.TextField()),
                ('forwhom_td_1_img', models.FileField(upload_to='test_1/static/')),
                ('forwhom_td_1', models.TextField()),
                ('forwhom_td_2_img', models.FileField(upload_to='test_1/static/')),
                ('forwhom_td_2', models.TextField()),
                ('forwhom_td_3_img', models.FileField(upload_to='test_1/static/')),
                ('forwhom_td_3', models.TextField()),
                ('forwhom_td_4_img', models.FileField(upload_to='test_1/static/')),
                ('forwhom_td_4', models.TextField()),
            ],
        ),
    ]
