# Generated by Django 3.1.7 on 2021-03-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0008_forwhom'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwhom',
            name='forwhom_td_3_img_byce',
            field=models.FileField(default='test_1/static/Bike.jpg', upload_to='test_1/static/'),
            preserve_default=False,
        ),
    ]
