# Generated by Django 3.1.7 on 2021-03-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0010_freeles'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeles',
            name='text_left_1',
            field=models.TextField(default='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeles',
            name='text_left_2',
            field=models.TextField(default='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freeles',
            name='text_left_3',
            field=models.TextField(default='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freeles',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='freeles',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='freeles',
            name='message',
            field=models.TextField(),
        ),
    ]
